config/routes.rb
Rails.application.routes.draw do
  resources :review_comments
  get 'reviews/index'
  devise_for :users
  resources :contacts
  #get 'home/index'
  get 'home/about'
  root 'home#index' #set as home page
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	has_one_attached :image
	belongs_to :user

	def self.search(search)
		if search
			contact = Contact.find_by(fname: search)
			if Contact
				self.where(userId: Contact)
			else
				Contact.all
			end
		else
			Contact.all
		end
	end
end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :contact	#user can have many contacts - association

before_commit :emailtypes
validate :CustomgemCM
         
def emailtypes
    require 'EmailType'
    user = User.last
    result = EmailType.emailchk(email)
    if result == 'Free email'
    user.update(emailtype: "Free Email Account")
    elsif result == 'Business email'
    user.update(emailtype: "Business Email Account")
    else
    user.update(emailtype: "Unknown Email Account")
    end
  end


def CustomgemCM
  return unless email.present?
    mxdomain = CustomgemCM.mxers(email)
    if mxdomain == "InvalidEmailDomain"         
       errors.add(:email, 'Invalid email domain specified')
      end
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.search (params[:search])
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = current_user.contact.build
  end

  # GET /contacts/1/edit
  def edit
  end

  

  # POST /contacts or /contacts.json
  def create
    @contact = current_user.contact.build(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @contact = current_user.contact.find_by(id: params[:id]) #the correct user is the current user that has been associated with the userid
    redirect_to contacts_path, notice: "Not Authorised" if @contact.nil? #if not the correct user throw an error message
 end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:fname, :lname, :email, :phone, :instagram, :user_id, :search)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/review_comments_controller.rb
class ReviewCommentsController < ApplicationController
  before_action :set_review_comment, only: %i[ show edit update destroy ]

  # GET /review_comments or /review_comments.json
  def index
    @review_comments = review_comments
  end

  # GET /review_comments/1 or /review_comments/1.json
  def show
  end

  # GET /review_comments/new
  def new
    @review_comment = ReviewComment.new
  end

  # GET /review_comments/1/edit
  def edit
  end

  # POST /review_comments or /review_comments.json
  def create
    @review_comment = ReviewComment.new(review_comment_params)

    respond_to do |format|
      if @review_comment.save
        format.html { redirect_to review_comment_url(@review_comment), notice: "Review comment was successfully created." }
        format.json { render :show, status: :created, location: @review_comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /review_comments/1 or /review_comments/1.json
  def update
    respond_to do |format|
      if @review_comment.update(review_comment_params)
        format.html { redirect_to review_comment_url(@review_comment), notice: "Review comment was successfully updated." }
        format.json { render :show, status: :ok, location: @review_comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /review_comments/1 or /review_comments/1.json
  def destroy
    @review_comment.destroy

    respond_to do |format|
      format.html { redirect_to review_comments_url, notice: "Review comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review_comment
      @review_comment = ReviewComment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_comment_params
      params.require(:review_comment).permit(:title, :body)
    end

    def search_query
      params[:query]
    end

    def review_comments
      query = ReviewComment.ransack(title_or_body_cont_any: search_query)
      query.result(distinct: true)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/review_comments_helper.rb
module ReviewCommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<br></br>
<br></br>
  

  <div class="field form-group">
    <%= form.text_field :fname,
        class:"form-control",
        placeholder: "First Name"%>
  </div>

  <div class="field form-group">
    <%= form.text_field :lname,
        class:"form-control",
        placeholder: "Last Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :email,
        class:"form-control",
        placeholder: "Email Address" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone,
        class:"form-control",
        placeholder: "Phone Number" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :instagram,
        class:"form-control",
        placeholder: "instagram" %>
  </div>

  <div class="field form-group">
   <%= form.text_field :user_id,
       id: :contact_user_id,
       class:"form-control",
       value:  current_user.id,
       type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-info"%>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<br></br>


<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>
<br/>

<%= link_to 'Show', @contact,  class:"btn btn-info" %> 
<%= link_to 'Back', contacts_path,  class:"btn btn-info" %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>
<br></br>
<br></br>

<h1>Contacts</h1>



<table class = "table table-striped table-hover">
      
  <thead class="thead-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Instagram</th>
      <th>User Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>  
    <% @contacts.each do |contact| %>
    <% if contact.user == current_user %>
      <tr>
        <td><%= contact.fname %></td>
        <td><%= contact.lname %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.instagram %></td>
        <td><%= contact.user_id %></td>
        <td><%= link_to 'Show', contact %></td>
        
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= form_tag(contacts_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag ("Search") %>
<% end %>

<br>

<%= link_to 'New Contact', new_contact_path, class:"btn btn-info" %>

app/views/contacts/new.html.erb
<br></br>
<br></br>
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>
<br/>

<%= link_to 'Back', contacts_path,  class:"btn btn-info" %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<br></br>
<br></br>


<p>
  <strong>First name:</strong>
  <%= @contact.fname %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.lname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Instagram:</strong>
  <%= @contact.instagram %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact), class:"btn btn-info" %> 
<%= link_to 'Back', contacts_path,  class:"btn btn-info" %>

app/views/home/_header.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Contact Management</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body id="page-top">
      <!--navigation -->
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
  <%= link_to 'Contacts', root_path, class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      	<%= link_to "About Us", home_about_path, class:"nav-link" %>
      </li>
   
      <% if user_signed_in? %>
      <li class="nav-item">
      	<%= link_to "Contacts", contacts_path, class:"nav-link" %>
      </li>

	  <li class="nav-item">
      	<%= link_to "New Contact", new_contact_path, class:"nav-link" %>
      </li>

      	<li class="nav-item">
      	<%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
      </li>

      <li class="nav-item">
      	<%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Reviews", review_comments_path, class:"nav-link" %>
      </li>

     <% else %>
      <li class="nav-item">
      	<%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
      	<%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
      </li>

      

    <% end %>

      
    </ul>
    
  </div>
</nav>

app/views/home/about.html.erb
<br></br>
<br></br>
<br></br>

<div class="about-section">
  <h1>About Us Page</h1>
  <p>Web page is hosted on Heroku</p>
  <p>Ruby on Rails</p>
</div>

<h2 style="text-align:center">Cloud Application Development</h2>
<div class="row">
  <div class="column">
    <div class="card">
      <div class="container">
        <h2>Alan Mellowes</h2>
        <p class="title"></p>
        <p>Project for cloud application development</p>
        <p>x18467362@student.ncirl.ie</p>
      </div>
    </div>
  </div>

</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
 
        <!-- Masthead-->
        <header class="masthead bg-info text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image-->
                <img class="masthead-avatar mb-5" src="assets/img/avataaars.svg" alt="..." />
                <!-- Masthead Heading-->
                <h1 class="masthead-heading text-uppercase mb-0">Contact Management</h1>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Masthead Subheading-->
                <p class="masthead-subheading font-weight-light mb-0">Manage Contacts - Find Friends - Reviews</p>
            </div>
        </header>
        <!-- Portfolio Section-->
        <section class="page-section portfolio" id="portfolio">
            <div class="container">
                <!-- Portfolio Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Quick Access</h2>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Grid Items-->
                <div class="row justify-content-center">
                    <!-- Portfolio Item 1-->
                    <div class="col-md-6 col-lg-4 mb-5">
                        <div class="portfolio-item mx-auto" data-bs-toggle="modal" data-bs-target="#portfolioModal1">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <img class="img-fluid" src="assets/img/portfolio/addfriend.PNG" alt="addfriend" />
                        </div>
                    </div>
                    <!-- Portfolio Item 2-->
                    <div class="col-md-6 col-lg-4 mb-5">
                        <div class="portfolio-item mx-auto" data-bs-toggle="modal" data-bs-target="#portfolioModal2">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <img class="img-fluid" src="assets/img/portfolio/signup.jpg" alt="signup" />
                        </div>
                    </div>
                    <!-- Portfolio Item 3-->
                    <div class="col-md-6 col-lg-4 mb-5">
                        <div class="portfolio-item mx-auto" data-bs-toggle="modal" data-bs-target="#portfolioModal3">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <img class="img-fluid" src="<%= asset_path ('reviews.PNG') %>" alt="reviews"/> 


                        </div>
                    </div>
                  
                </div>
            </div>
        </section>
        <!-- About Section-->
        <section class="page-section bg-info text-white mb-0" id="about">
            <div class="container">
                <!-- About Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-white">About</h2>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- About Section Content-->
                <div class="row">
                    <div class="col-lg-4 ms-auto"><p class="lead">Cloud Application Development</p></div>
                    <div class="col-lg-4 me-auto"><p class="lead">Alan Mellowes | x18467362@student.ncirl.ie</p></div>
                </div>
                <!-- About Section Button-->
                <div class="text-center mt-4">
            </div>
        </section>
        <!-- Contact Section-->
        <section class="page-section" id="contact">
            <div class="container">
                <!-- Contact Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Contact Me</h2>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Contact Section Form-->
                <div class="row justify-content-center">
                    <div class="col-lg-8 col-xl-7">
                        <!-- API for form-->
                        <form id="contactForm" data-sb-form-api-token="09629937-8d82-4090-85b2-ff442aefbaf1">
                            <!-- Name input-->
                            <div class="form-floating mb-3">
                                <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />
                                <label for="name">Full name</label>
                                <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                            </div>
                            <!-- Email address input-->
                            <div class="form-floating mb-3">
                                <input class="form-control" id="email" type="email" placeholder="name@example.com" data-sb-validations="required,email" />
                                <label for="email">Email address</label>
                                <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                                <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                            </div>
                            <!-- Phone number input-->
                            <div class="form-floating mb-3">
                                <input class="form-control" id="phone" type="tel" placeholder="(123) 456-7890" data-sb-validations="required" />
                                <label for="phone">Phone number</label>
                                <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                            </div>
                            <!-- Message input-->
                            <div class="form-floating mb-3">
                                <textarea class="form-control" id="message" type="text" placeholder="Enter your message here..." style="height: 10rem" data-sb-validations="required"></textarea>
                                <label for="message">Message</label>
                                <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                            </div>
                            <!-- Submit success message-->
                            <!-- users will see when the form-->
                            <!-- has successfully submitted-->
                            <div class="d-none" id="submitSuccessMessage">
                                <div class="text-center mb-3">
                                    <div class="fw-bolder">Form submission successful!</div>
                                    I will be in contact soon.
                                    <br />
                                </div>
                            </div>
                            <!-- Submit error message-->
                            <!---->
                            <!-- This is what your users will see when there is-->
                            <!-- an error submitting the form-->
                            <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                            <!-- Submit Button-->
                            <button class="btn btn-info btn-xl disabled" id="submitButton" type="submit">Send</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <!-- Footer Location-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Location</h4>
                        <p class="lead mb-0">
                            National College of Ireland
                            <br />
                            Dublin, Ireland
                        </p>
                    </div>
                    <!-- Footer Social Icons-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Around the Web</h4>
                        <a class="btn btn-outline-light btn-social mx-1" href="https://www.facebook.com/"><i class="fab fa-fw fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="https://twitter.com/"><i class="fab fa-fw fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="https://ie.linkedin.com/"><i class="fab fa-fw fa-linkedin-in"></i></a>
                    </div>
                    <!-- Footer About Text-->
                    <div class="col-lg-4">
                        <h4 class="text-uppercase mb-4">Project</h4>
                        <p class="lead mb-0">
                            This is my cloud application project
                        </p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Copyright Section-->
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright &copy; Contact Management 2022 - Alan Mellowes</small></div>
        </div>
        
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Contacts</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render 'home/header' %>

    <div class = "container">
      <br/>
    <%= yield %>
  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/review_comments/_form.html.erb
<%= form_with(model: review_comment) do |form| %>
  <% if review_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review_comment.errors.count, "error") %> prohibited this review_comment from being saved:</h2>

      <ul>
        <% review_comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/review_comments/_review_comment.html.erb
      <tr>
        <td><%= review_comment.title %></td>
        <td><%= review_comment.body %></td>
      </tr>

app/views/review_comments/edit.html.erb
<br></br>
<br></br>

<h1>Editing Review Comment</h1>

<%= render 'form', review_comment: @review_comment %>

<%= link_to 'Show', @review_comment %> |
<%= link_to 'Back', review_comments_path %>

app/views/review_comments/index.html.erb
<br></br>
<br></br>
<p id="notice"><%= notice %></p>

<h1>Review Comments</h1>

<%= form_with url: review_comments_path, method: :get do |form| %>
  <%= form.text_field :query %>
    <%= form.submit "Search" %>
   <% end %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    <%= render @review_comments %>

  </tbody>
</table>

<br>

<%= link_to 'New Review Comment', new_review_comment_path %>

app/views/review_comments/new.html.erb
<br></br>
<br></br>


<h1>New Review Comment</h1>

<%= render 'form', review_comment: @review_comment %>

<%= link_to 'Back', review_comments_path %>

app/views/review_comments/show.html.erb
<br></br>
<br></br>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @review_comment.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @review_comment.body %>
</p>

<%= link_to 'Edit', edit_review_comment_path(@review_comment) %> |
<%= link_to 'Back', review_comments_path %>